config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :newsletters, only: [:index, :show, :new, :create]

  root 'newsletters#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
    has_many :sections, inverse_of: :newsletter

    validates :title, presence: true
    validates :address, presence: true
    validates :date, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  has_ancestry

  belongs_to :newsletter, inverse_of: :sections

  validates :title, presence: true

  def contents
    self.children.map do|child|
      { title: child.title, content: child.content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  def index
    @newsletters = Newsletter.all
  end

  def show
    @newsletter = Newsletter.find(params[:id])
  end

  def new
    @newsletter = Newsletter.new
  end

  def create
    @newsletter = Newsletter.new(newsletter_params)

    if @newsletter.save
      redirect_to newsletters_path
    else
      render 'new'
    end
  end

  private

  def newsletter_params
    params.require(:newsletter).permit(:title, :address, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title ChurchNews
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/newsletters/index.html.haml
%h1 Newsletters
%table
  %tr
    %th Title
    %th Address
    %th Date

  - @newsletters.each do |newsletter|
    %tr
      %td
        = newsletter.title
      %td
        = newsletter.address
      %td
        = newsletter.date || '--'
      %td
        = link_to 'Show', newsletter_path(newsletter)

= link_to "New", new_newsletter_path